"""Versioned API contracts for inspection and later conversation layers."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class RetrievalRequest(BaseModel):
    query: str = Field(min_length=1, max_length=1000)
    character_id: str | None = None
    # ``chat`` is retained as a backwards-compatible alias for older clients;
    # the browser and new callers use the two explicit conversation modes.
    mode: Literal["immersive", "assistant", "chat"] = "immersive"
    limit: int = Field(default=8, ge=1, le=20)


class Citation(BaseModel):
    document_id: str
    page_id: str
    title: str
    source_type: str
    canonical_url: str | None = None
    local_path: str | None = None
    source_license: str | None = None


class RetrievalHit(BaseModel):
    citation: Citation
    text: str
    score: float
    lexical_rank: int | None = None
    vector_rank: int | None = None
    metadata: dict[str, Any]


class ConversationIdentity(BaseModel):
    """A fixed project invariant rather than a field supplied by the caller."""

    user_role: Literal["分析员"] = "分析员"
    policy: str = "当前用户即分析员；聊天与助手模式均不得改变角色与分析员的既有叙事关系。"


class RetrievalResponse(BaseModel):
    query: str
    mode: Literal["immersive", "assistant", "chat"]
    character_id: str | None
    conversation_identity: ConversationIdentity
    fusion: Literal["rrf", "lexical_only"]
    vector_available: bool
    results: list[RetrievalHit]


class AnalystContentBlock(BaseModel):
    """One analyst-authored block for a chat turn.

    ``message`` remains the backwards-compatible plain-text request field.
    The optional blocks let the in-person client distinguish a spoken line
    from an explicitly authored analyst action without granting the model the
    ability to invent actions on the analyst's behalf.
    """

    type: Literal["speech", "action", "message"]
    text: str = Field(min_length=1, max_length=1200)


class MVPChatRequest(BaseModel):
    character_id: str = Field(min_length=1, max_length=120)
    message: str = Field(min_length=1, max_length=4000)
    session_id: str | None = Field(default=None, max_length=160)
    # Character chat histories stay isolated, while this ID keeps the
    # present-time world scene consistent when the user switches characters.
    world_session_id: str | None = Field(default=None, max_length=160)
    # Immersive companionship is the safe/default mode.  Assistant mode is an
    # explicit opt-in and is isolated at the session boundary.
    mode: Literal["immersive", "assistant"] = "immersive"
    communication_channel: Literal["in_person", "text"] | None = None
    presence_action: Literal["join_character"] | None = None
    costume_context: str | None = Field(default=None, max_length=240)
    # Optional idempotency key generated by the client. Older clients can omit
    # it and retain the pre-persistence request behavior.
    client_message_id: str | None = Field(default=None, min_length=8, max_length=160)
    # Optional structured analyst input.  The backend validates that an
    # ``action`` can only be submitted in an in-person turn; older clients
    # simply omit this field and continue to send the ``message`` string.
    analyst_content_blocks: list[AnalystContentBlock] = Field(default_factory=list, max_length=8)
    limit: int = Field(default=8, ge=1, le=12)


class MVPFeedbackRequest(BaseModel):
    character_id: str = Field(min_length=1, max_length=120)
    session_id: str = Field(min_length=1, max_length=160)
    message_id: str | None = Field(default=None, max_length=160)
    selected_options: list[str] = Field(default_factory=list, max_length=10)
    category: Literal[
        "character_portrayal",
        "knowledge_memory",
        "conversation_experience",
        "client_function",
        "other",
    ] | None = None
    free_text: str = Field(default="", max_length=4000)
    mode: Literal["immersive", "assistant"] | None = None
    communication_channel: Literal["in_person", "text"] | None = None
    registry_version: str | None = Field(default=None, max_length=80)
    client_version: str | None = Field(default=None, max_length=80)
    message_excerpt: str = Field(default="", max_length=1200)
    answer_excerpt: str = Field(default="", max_length=1800)


class MVPFeedbackTriageRequest(BaseModel):
    status: Literal["pending_triage", "planned", "resolved", "ignored"]
    note: str = Field(default="", max_length=2000)


class MVPFeedbackIssueStatusRequest(BaseModel):
    status: Literal[
        "open",
        "needs_verification",
        "fixed_verified",
        "not_reproduced",
        "duplicate",
    ]
    note: str = Field(default="", max_length=2000)


class GraphEdge(BaseModel):
    edge_id: str
    from_id: str
    relation_type: str
    to_id: str
    evidence_page_ids: list[str]
    confidence: str
    review_status: str
    source_types: list[str] = Field(default_factory=list)
    narrative_scope: Literal["stable", "situational", "costume_specific", "unknown"] = "unknown"


class GraphNeighborhood(BaseModel):
    node: dict[str, Any]
    edges: list[GraphEdge]
    adjacent_nodes: list[dict[str, Any]]


class RelationReviewDecision(BaseModel):
    decision: Literal["approved", "rejected"]
    reviewer_id: str = Field(min_length=1, max_length=120)
    note: str = Field(default="", max_length=2000)
    from_node_id: str | None = Field(default=None, max_length=240)
    to_node_id: str | None = Field(default=None, max_length=240)


class EntityNodeReviewDecision(BaseModel):
    """Human decision for a proposed location/event graph node."""

    decision: Literal["approved", "rejected"]
    reviewer_id: str = Field(min_length=1, max_length=120)
    note: str = Field(default="", max_length=2000)


class StageLockResponse(BaseModel):
    code: Literal["conversation_stage_locked"]
    message: str
    required_stages: list[str]
    conversation_identity: ConversationIdentity
