const apiRoot = "/public/v1";
const dbName = "project-snow-public";
const dbVersion = 1;
const state = { config:null, credential:null, credentialExpiresAt:0, provider:"", model:"", characters:[], selected:"", stateByCharacter:new Map(), latest:new Map() };
const $ = (id) => document.getElementById(id);
const errorMessages = {
  invalid_request:"请求内容不完整，请确认模型厂商、API Key 和模型 ID 已填写。",
  provider_not_enabled:"该模型厂商尚未启用，请刷新页面或选择其他厂商。",
  provider_credential_rejected:"API Key 被模型厂商拒绝，请检查密钥、余额和模型权限。",
  provider_model_discovery_failed:"无法获取模型列表；你仍可手动填写正确的模型 ID。",
  provider_network_error:"暂时无法连接模型厂商，请稍后重试。",
  provider_timeout:"模型厂商响应超时，请稍后重试。",
  provider_rate_limited:"模型厂商触发了频率限制，请稍后重试。",
  provider_request_failed:"模型厂商拒绝了本次请求，请检查模型 ID 和账户权限。",
  turnstile_required:"人机验证未完成，请稍后重试。",
  turnstile_unavailable:"人机验证组件加载失败，请刷新页面后重试。",
  rate_limit_exceeded:"操作过于频繁，请稍后重试。",
  credential_invalid:"模型会话已失效，请重新输入 API Key。",
  request_failed:"请求失败，请稍后重试。",
};

function id() { return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function text(value) { return String(value || ""); }
function escape(value) { const span = document.createElement("span"); span.textContent = text(value); return span.innerHTML; }
function sessionKey() { return "project-snow-public:byok"; }
function clearCredential() { sessionStorage.removeItem(sessionKey()); state.credential=""; state.credentialExpiresAt=0; }
function configured() { if(state.credentialExpiresAt && state.credentialExpiresAt<=Date.now()) clearCredential(); return Boolean(state.credential && state.provider && state.model); }

function openDB() { return new Promise((resolve, reject) => { const request = indexedDB.open(dbName, dbVersion); request.onupgradeneeded = () => { const db=request.result; if(!db.objectStoreNames.contains("threads")) db.createObjectStore("threads", { keyPath:"characterId" }); }; request.onsuccess=()=>resolve(request.result); request.onerror=()=>reject(request.error); }); }
async function dbGet(characterId) { const db=await openDB(); return new Promise((resolve,reject)=>{ const tx=db.transaction("threads","readonly"); const request=tx.objectStore("threads").get(characterId); request.onsuccess=()=>resolve(request.result || {characterId,messages:[],summary:"",statePackage:"",turnCount:0}); request.onerror=()=>reject(request.error); }); }
async function dbPut(record) { const db=await openDB(); return new Promise((resolve,reject)=>{ const tx=db.transaction("threads","readwrite"); tx.objectStore("threads").put(record); tx.oncomplete=resolve; tx.onerror=()=>reject(tx.error); }); }
async function dbDelete(characterId) { const db=await openDB(); return new Promise((resolve,reject)=>{ const tx=db.transaction("threads","readwrite"); tx.objectStore("threads").delete(characterId); tx.oncomplete=resolve; tx.onerror=()=>reject(tx.error); }); }
async function dbClear() { const db=await openDB(); return new Promise((resolve,reject)=>{ const tx=db.transaction("threads","readwrite"); tx.objectStore("threads").clear(); tx.oncomplete=resolve; tx.onerror=()=>reject(tx.error); }); }
async function storageBytes() { const db=await openDB(); return new Promise((resolve,reject)=>{ const tx=db.transaction("threads","readonly"); const request=tx.objectStore("threads").getAll(); request.onsuccess=()=>resolve(new Blob([JSON.stringify(request.result)]).size); request.onerror=()=>reject(request.error); }); }
function formatBytes(bytes) { return bytes < 1024 ? `${bytes} B` : bytes < 1048576 ? `${(bytes/1024).toFixed(1)} KB` : `${(bytes/1048576).toFixed(1)} MB`; }

async function request(path, options={}) { const headers={...(options.headers||{})}; if(options.method && options.method!=="GET") headers["Content-Type"]="application/json"; const response=await fetch(`${apiRoot}${path}`, { credentials:"same-origin", ...options, headers }); const payload=await response.json().catch(()=>({})); if(!response.ok) throw new Error(payload?.detail?.code || "request_failed"); return payload; }
function showError(id, error) { const code=error instanceof Error ? error.message : text(error); $(id).textContent=errorMessages[code] || errorMessages.request_failed; }

async function waitForTurnstile() { for(let attempt=0;attempt<100;attempt+=1) { if(window.turnstile) return window.turnstile; await new Promise(resolve=>setTimeout(resolve,100)); } return null; }
async function tokenFor(action) { const sitekey=state.config?.turnstile_site_key; if(!sitekey) return "development-bypass"; const turnstile=await waitForTurnstile(); if(!turnstile) throw new Error("turnstile_unavailable"); return new Promise((resolve,reject)=>{ const container=document.createElement("div"); container.className="turnstile-container"; document.body.append(container); let widget=""; const cleanup=()=>{ if(widget!=="") turnstile.remove(widget); container.remove(); }; try { widget=turnstile.render(container,{sitekey,action,execution:"execute",appearance:"interaction-only",callback:(token)=>{cleanup();resolve(token);},"error-callback":()=>{cleanup();reject(new Error("turnstile_required"));},"expired-callback":()=>{cleanup();reject(new Error("turnstile_required"));}}); turnstile.execute(widget); } catch(error) { cleanup(); reject(new Error("turnstile_unavailable")); } }); }
function attachTurnstile() { if (!state.config?.turnstile_site_key || document.querySelector("script[data-turnstile]")) return; const script=document.createElement("script"); script.src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit"; script.async=true; script.defer=true; script.dataset.turnstile="true"; document.head.append(script); }

async function loadConfig() { state.config=await request("/config",{headers:{}}); $("version-badge").textContent=`应用 ${state.config.app_version} · 数据 ${state.config.data_version}`; $("github-link").href=state.config.source_links.project_snow; $("website-github-link").href=state.config.source_links.mywebsite; $("releases-link").href=state.config.source_links.releases; $("provider-select").innerHTML=state.config.providers.map((p)=>`<option value="${escape(p.provider_id)}">${escape(p.display_name)}</option>`).join(""); if(!state.config.providers.length) showError("setup-error","私有验收尚未启用任何模型厂商；请先完成真实 API Key 冒烟测试。"); attachTurnstile(); const stored=sessionStorage.getItem(sessionKey()); if(stored) { try { const saved=JSON.parse(stored); if(saved.expiresAt > Date.now()) { state.credential=saved.credential; state.credentialExpiresAt=saved.expiresAt; state.provider=saved.provider; state.model=saved.model; openChat(); return; } } catch {} clearCredential(); } }

async function issueCredential() { const provider=$("provider-select").value; const apiKey=$("api-key").value; if(!apiKey) throw new Error("请先输入 API Key。"); const payload=await request("/byok/session",{method:"POST",body:JSON.stringify({provider,api_key:apiKey,turnstile_token:await tokenFor("byok-session"),accepted_transit_notice:$("notice-transit").checked,accepted_cost_notice:$("notice-cost").checked,accepted_local_history_notice:$("notice-history").checked})}); state.credential=payload.credential; state.provider=provider; state.credentialExpiresAt=Date.parse(payload.expires_at); $("api-key").value=""; return payload; }
async function connect(event) { event.preventDefault(); showError("setup-error",""); const model=$("model-id").value.trim(); if(!model) return showError("setup-error","请填写或选择模型 ID。 "); try { if(!state.credential || state.provider!==$("provider-select").value) await issueCredential(); state.model=model; sessionStorage.setItem(sessionKey(),JSON.stringify({credential:state.credential,provider:state.provider,model,expiresAt:state.credentialExpiresAt})); openChat(); } catch(error) { showError("setup-error",error); } }
async function discoverModels() { showError("setup-error",""); try { if(!state.credential || state.provider!==$("provider-select").value) await issueCredential(); const payload=await request("/byok/models",{method:"POST",body:JSON.stringify({provider:state.provider,credential:state.credential,request_id:id()})}); const select=$("discovered-models"); select.innerHTML=`<option value="">选择已发现模型（也可手动填写）</option>${payload.models.map((model)=>`<option value="${escape(model)}">${escape(model)}</option>`).join("")}`; select.hidden=false; select.onchange=()=>{ if(select.value) $("model-id").value=select.value; }; } catch(error) { showError("setup-error",error); } }

async function openChat() { $("setup-view").hidden=true; $("chat-view").hidden=false; await loadCharacters(); }
async function loadCharacters() { const payload=await request("/characters",{headers:{}}); state.characters=payload.characters; renderCharacters(); $("history-character").innerHTML=state.characters.map(c=>`<option value="${escape(c.character_id)}">${escape(c.display_name)}</option>`).join(""); if(!state.selected && state.characters[0]) await selectCharacter(state.characters[0].character_id); }
function renderCharacters() { const query=$("character-search").value.trim().toLowerCase(); $("character-list").innerHTML=state.characters.filter(c=>!query || `${c.display_name} ${c.aliases.join(" ")}`.toLowerCase().includes(query)).map(c=>{ const avatar=c.avatar ? `<img class="avatar" src="${escape(c.avatar)}" alt="" />` : `<span class="avatar">${escape(c.display_name.slice(0,1))}</span>`; return `<button class="character" role="option" aria-selected="${c.character_id===state.selected}" data-character="${escape(c.character_id)}">${avatar}<span>${escape(c.display_name)}<small>${escape(c.license)}</small></span></button>`; }).join(""); document.querySelectorAll("[data-character]").forEach(button=>button.onclick=()=>selectCharacter(button.dataset.character)); }
async function selectCharacter(characterId) { state.selected=characterId; renderCharacters(); const character=state.characters.find(c=>c.character_id===characterId); $("conversation-header").innerHTML=`<div><h1>${escape(character.display_name)}</h1><p>纯文本沉浸式对话 · 仅本地保存历史</p></div><span id="service-state" class="state">已连接</span>`; const thread=await dbGet(characterId); state.stateByCharacter.set(characterId,thread); renderMessages(thread.messages || []); $("message-input").disabled=false; $("send-button").disabled=false; }
function renderMessages(messages) { const root=$("messages"); if(!messages.length) { root.innerHTML='<p class="empty">从一句问候开始吧。你的历史将只保存在此浏览器。</p>'; return; } root.innerHTML=messages.map(message=>`<article class="message ${message.role}"><span class="meta">${message.role==="user"?"你":"角色"}</span>${escape(message.content)}</article>`).join(""); root.scrollTop=root.scrollHeight; }
function historyForRequest(messages) { return messages.slice(-24).map(message=>({role:message.role,content:message.content})); }
async function send(event) { event.preventDefault(); const input=$("message-input"), message=input.value.trim(); if(!message || !state.selected) return; if(!configured()) { await changeModel(); return showError("setup-error","会话凭证已过期，请重新输入 API Key。"); } const thread=state.stateByCharacter.get(state.selected) || await dbGet(state.selected); const previous=[...(thread.messages||[])]; thread.messages=[...previous,{role:"user",content:message,createdAt:Date.now()}]; input.value=""; updateCount(); renderMessages(thread.messages); $("send-button").disabled=true; $("service-state").textContent="生成中"; try { const response=await fetch(`${apiRoot}/chat/stream`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({request_id:id(),provider:state.provider,credential:state.credential,model:state.model,character_id:state.selected,message,recent_history:historyForRequest(previous),history_summary:thread.summary||"",state_package:thread.statePackage||""})}); if(!response.ok) { const payload=await response.json().catch(()=>({})); throw new Error(payload?.detail?.code || "chat_failed"); } const reader=response.body.getReader(), decoder=new TextDecoder(); let buffer="", answer="", statePackage="", degraded=[]; while(true) { const {value,done}=await reader.read(); if(done) break; buffer+=decoder.decode(value,{stream:true}); const blocks=buffer.split("\n\n"); buffer=blocks.pop(); for(const block of blocks) { const event=(block.match(/^event: (.+)$/m)||[])[1]; const data=(block.match(/^data: (.+)$/m)||[])[1]; if(!event||!data) continue; const payload=JSON.parse(data); if(event==="delta") { answer+=payload.text; renderMessages([...thread.messages,{role:"assistant",content:answer}]); } if(event==="state") statePackage=payload.state_package; if(event==="done") degraded=payload.degraded_services||[]; if(event==="error") throw new Error(payload.code||"chat_failed"); } } thread.messages=[...thread.messages,{role:"assistant",content:answer,createdAt:Date.now()}]; thread.statePackage=statePackage||thread.statePackage||""; thread.turnCount=(thread.turnCount||0)+1; await dbPut(thread); state.stateByCharacter.set(state.selected,thread); if(thread.turnCount%12===0) { try { await offerSummary(thread); } catch(summaryError) { $("service-state").textContent=`摘要失败：${summaryError.message||"request_failed"}`; } } else { $("service-state").textContent=degraded.length ? `降级：${degraded.join("、")}` : "已连接"; } } catch(error) { thread.messages=previous; renderMessages(previous); showError("feedback-error",error); $("service-state").textContent="请求失败"; } finally { $("send-button").disabled=false; } }
async function offerSummary(thread) { if(!confirm("已经新增 12 轮对话。现在生成本地摘要吗？这会额外调用一次你的模型，并计入每日 200 轮额度。")) { $("service-state").textContent="摘要已跳过"; return; } const turns=(thread.messages||[]).slice(-24).map(({role,content})=>({role,content})); const payload=await request("/chat/summarize",{method:"POST",body:JSON.stringify({request_id:id(),provider:state.provider,credential:state.credential,model:state.model,character_id:state.selected,turns,previous_summary:thread.summary||""})}); thread.summary=payload.summary||thread.summary||""; await dbPut(thread); $("service-state").textContent="本地摘要已更新"; }
function updateCount() { $("input-count").textContent=`${$("message-input").value.length} / 2000`; }

async function submitFeedback(event) { event.preventDefault(); showError("feedback-error",""); const thread=state.selected ? await dbGet(state.selected) : {messages:[]}; const lastUser=[...(thread.messages||[])].reverse().find(m=>m.role==="user")?.content||""; const lastAnswer=[...(thread.messages||[])].reverse().find(m=>m.role==="assistant")?.content||""; try { const payload=await request("/feedback",{method:"POST",body:JSON.stringify({request_id:id(),body:$("feedback-body").value,qq:$("feedback-qq").value,turnstile_token:await tokenFor("feedback"),character_id:state.selected,provider:state.provider,model:state.model,user_message:lastUser,assistant_answer:lastAnswer,request_stage:"immersive-web",error_code:"",degraded_services:[],ui_surface:"immersive-web"})}); $("feedback-dialog").close(); $("feedback-form").reset(); alert(`反馈已提交，编号：${payload.feedback_code}`); } catch(error) { showError("feedback-error",error); } }
async function openHistory() { $("history-dialog").showModal(); $("storage-usage").textContent=`当前浏览器记录约占 ${formatBytes(await storageBytes())}。`; }
async function changeModel() { clearCredential(); $("chat-view").hidden=true; $("setup-view").hidden=false; }

$("byok-form").onsubmit=connect; $("discover-models").onclick=discoverModels; $("composer").onsubmit=send; $("message-input").oninput=updateCount; $("character-search").oninput=renderCharacters; $("feedback-open").onclick=()=>$("feedback-dialog").showModal(); $("feedback-form").onsubmit=submitFeedback; $("history-settings").onclick=openHistory; $("change-model").onclick=changeModel; $("delete-character-history").onclick=async()=>{await dbDelete($("history-character").value); if($("history-character").value===state.selected) await selectCharacter(state.selected); await openHistory();}; $("clear-all-history").onclick=async()=>{if(confirm("确定清空当前浏览器的全部 Project Snow 聊天记录吗？")){await dbClear(); if(state.selected) await selectCharacter(state.selected); await openHistory();}}; document.querySelectorAll("[data-close]").forEach(button=>button.onclick=()=>$(button.dataset.close).close());
loadConfig().catch(error=>showError("setup-error",error));
